spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 대문자 소문자 구분
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # fintech-mysql
    url: jdbc:mysql://fintech-mysql:3306/fintech?serverTimezone=UTC&characterEncoding=UTF-8
    username: fintech
    password: fintech
  redis:
    host: fintech-redis
    port: 6379
