version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - fintech

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - fintech
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    container_name: api
    image: api:0.0.2
    ports:
      - "80:80"
    networks:
      - fintech

  consummer:
    container_name: consumer
    image: consumer:0.0.2
    ports:
      - "8080:8080"
    networks:
      - fintech

  css:
    container_name: css
    image: css:0.0.2
    ports:
      - "8081:8081"
    networks:
      - fintech

  nginx:
    container_name: nginx
    image: custom_nginx:1.0
    ports:
      - "8085:8085"
    networks:
      - fintech

networks:
  fintech:
    driver: bridge
